"""
The module contains functions to tokenize the recipe dataframe
"""

import logging
from logging.handlers import RotatingFileHandler
from typing import Iterable, List, Set, Tuple

import pandas as pd
import spacy
from spacy.tokens import Doc

# Messages de log à différents niveaux
logging.debug("Ceci est un message de niveau DEBUG")
logging.info("Ceci est un message de niveau INFO")
logging.warning("Ceci est un message de niveau WARNING")
logging.error("Ceci est un message de niveau ERROR")
logging.critical("Ceci est un message de niveau CRITICAL")

# Création d'un logger pour ce module
logger = logging.getLogger(__name__)

# Définir le niveau de log sur INFO
logger.setLevel(logging.INFO)

# Création d'un handler permettant la rotation des logs, avec format compréhensible

file_handler = RotatingFileHandler(
    "tokenization.log", maxBytes=5 * 1024 * 1024, backupCount=5, encoding="utf-8"
)
file_handler.setLevel(logging.INFO)
handler_format = logging.Formatter(
    "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
file_handler.setFormatter(handler_format)

console_handler = logging.StreamHandler()
console_handler.setFormatter(handler_format)
console_handler.setLevel(logging.INFO)

# Éviter d'ajouter plusieurs handlers si le module est importé plusieurs fois
if not logger.handlers:
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)


def extract_text_from_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    The function takes the recipe dataframe to extract only recipe name and recipe
    description and cconcatenate them in a single column for tokenization.

    Parameters:
    -----------
    df: pd.DataFrame
        a dataframe containing the recipes to be searched

    Returns:
    --------
    data_text: pd.DataFrame
        a dataframe with merged colums for name and description
    """

    test_columns = ["name", "description"]
    missing_columns = [col for col in test_columns if col not in df.columns]
    if len(missing_columns) == len(test_columns):
        logger.error("Columns 'Name' and 'Description' are missing")
        raise KeyError("Name, Description")
    if len(missing_columns) > 0:
        logger.warning(
            "Missing columns in the dataframe. Unexpected results may be found"
        )
    else:
        logger.info("Dataframe is correctly built")

    mask = df[["name", "description"]].notna().any(axis=1)
    data_text = df.loc[mask, ["name", "description"]].copy()
    data_text["full_text"] = (
        data_text["name"].fillna("") + " " + data_text["description"].fillna("")
    )
    logger.info("Name and description extracted from dataframe")
    return data_text


def extract_tokens_from_df(df: pd.DataFrame) -> Tuple[Iterable[Doc], Set[str]]:
    """
    The function creates a nlp pipeline to extract tokens the recipe
    name and description

    Parameters:
    -----------
    df: pd.DataFrame
        a dataframe containing the recipes concatenated

    Returns:
    --------
    docs: Iterable[Doc]
        a list of docs generated by the NLP pipeline
    stopwords: Set[str]
        a list of stopwords from the same pipe
    """
    nlp = spacy.load("en_core_web_sm", disable=["ner"])
    stopwords = {w.lower() for w in nlp.Defaults.stop_words}

    try:
        df["full_text"]
    except KeyError:
        logger.error("No column existing for tokenization")

    texts = df["full_text"].tolist()
    docs = nlp.pipe(texts, batch_size=50, n_process=4)

    logger.info("Tokenization complete")

    return docs, stopwords


def extract_tokens_from_doc(doc: Doc, stopwords: Set[str]) -> List[str]:
    """
    The function selects the interesting tokens for each doc.
    Interesting tokens are lemmas with position noun and adjective.
    It excludes other words, numbers and stopwords

    Parameters:
    ----------
    doc: Doc
        a doc extracted with the NLP pipe

    stopwords: Set[str]
        the list of stopwords from the same pipe

    Returns:
    --------
    token.lemma: List[str]
        a list of interesting tokens

    """
    return [
        token.lemma_.lower()
        for token in doc
        if token.is_alpha
        and token.pos_ in {"NOUN", "ADJ"}
        and token.lemma_.lower() not in stopwords
    ]


def store_tokens_in_df(
    docs: Iterable[Doc], stopwords: Set[str], df: pd.DataFrame
) -> pd.DataFrame:
    """
    The function loops on the docs to extract the tokens and store them
    in a new column of the recipe dataframe.

    Parameters:
    -----------
    docs: Iterable[Doc]
        a list of doc extracted from the recipe dataframe
    stopwords: Set[str]
        the list of stopwords from the NLP pipe
    df: pd.DataFrame
        the recipe dataframe in which storing the results

    Returns:
    --------
    df: pd.DataFra
      the recipe dataframe updated with the tokens
    """

    tokens_extracted = [extract_tokens_from_doc(doc, stopwords) for doc in docs]

    logger.info("Tokens extracted")

    if len(tokens_extracted) != len(df):
        raise RuntimeError("Mismatch between number of documents and dataframe size")

    if "tokens" not in df.columns:
        df["tokens"] = pd.Series([None] * len(df), index=df.index, dtype=object)
    else:
        df["tokens"] = df["tokens"].astype(object)

    tokens_series = pd.Series(tokens_extracted, index=df.index, dtype=object)
    df.loc[df.index, "tokens"] = tokens_series

    logger.info("Tokens stored in dataframe")

    return df


def extract_tokens_from_string(query_text: str) -> List[str]:
    """
    This function extracts interesting tokens from the user search on the webapp

    Parameters:
    -----------
    query_text: str
        A string captured from the search bar of the webapp

    Returns:
    --------
    tokens_extracted: List[str]
        The list of interesting tokens from the search
    """

    if not query_text:
        logger.error("User has indicated an empty string for the search")
        raise ValueError("Searched string empty")

    nlp = spacy.load("en_core_web_sm", disable=["ner"])
    stopwords = {w.lower() for w in nlp.Defaults.stop_words}
    docs = list(nlp.pipe(query_text))  # convert generator → list of Docs
    query_doc = docs[0]
    tokens_extracted = extract_tokens_from_doc(query_doc, stopwords)
    logger.info("User search tokenized")

    return tokens_extracted
